config/routes.rb
Rails.application.routes.draw do
  get 'appearances/new'

  get 'appearances/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :guests
  resources :episodes
  resources :appearances
end

app/models/appearance.rb
class Appearance < ApplicationRecord
    belongs_to :guest_id
    belongs_to :episode_id

    validates :rating, :numericality => {:greater_than_orequal_to => 1}
    validates :rating, :numericality => {:less_than_or_equal_to => 5}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :appearances
  has_many :guests, through: :appearances

  def get_rating
    self.appearances.average(:rating).to_i
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :appearances
  has_many :episodes, through: :appearances
end

app/controllers/appearances_controller.rb
class AppearancesController < ApplicationController

    def new
      @appearance = Appearance.new
    end
  
    def create 
        @appearance = Appearance.new(appearance_params)
        if @appearance.save
            redirect_to @appearance
        else
            render :new
        end
    end
  

  
    def appearance_params 
      params.require(:appearance).permit(:guest_id, :episode_id, :rating)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
  end

  def show 
    @episode = Episode.find(params[:id])
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/appearances/new.html.erb
<h1>This is my new appearances page</h1>

<h2>I display the errors</h2>
  <% if @appearance.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@appearance.errors.count, "error") %> not saved:</h2>
 
    <ul>
    <% @appearance.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@appearance) do |f| %>
  <%= f.label :guest %>: 
  <%= f.collection_select :guest_id, Guest.all, :id, :name%><br><br>

  <%= f.label :episode %>:
  <%= f.collection_select :episode_id, Episode.all, :id, :date %><br><br>

  <%= f.label "Enter a rating from 1 to 5:" %>
  <%
=begin%>
 <%= f.select :rating, (1..5)%><br><br> 
<%
=end%>

<%= f.text_field :rating %><br><br>

  <%= f.submit "Create" %>

<% end %>

app/views/episodes/index.html.erb
<h1>All Episodes</h1>

<ul>
  <% @episodes.each do |episode| %>
    <li><%= link_to "Episode #{episode.number}", episode_path(episode) %> - <%= episode.date.strftime("%B %d, %Y")%></li>
  <% end %>
</ul>
<%= link_to 'New Appearance', new_appearance_path %>

app/views/episodes/show.html.erb
<h1>Episode Details</h1>

<h3>Episode date: <%= @episode.date %></h3><br><br>

<h3>Episode rating: <%= @episode.get_rating %></h3><br>
<h3>Guests that appeared on this episode:</h3>
<ul>
  <% @episode.guests.each do |guest| %>
    <li><%= link_to guest.name, guest_path(guest) %></li>
  <% end %>
</ul>

app/views/guests/index.html.erb
<h1>All The Guests</h1>

<ul>
  <% @guests.each do |guest| %>
    <li><%= link_to guest.name, guest_path(guest) %></li>
  <% end %>
</ul>
<%= link_to 'New Appearance', new_appearance_path %>

app/views/guests/show.html.erb
<h1>This is the guest show page</h1>

<p>Guest name:<%= @guest.name %></p><br>

<p>Guest Occupation:<%= @guest.occupation %></p>

<h1>The list of the episodes this guest has been in:</h1>

<% @guest.appearances.each do |appearance| %>
   <p>Appearance Date :<%= appearance.episode.date %></p><br>

   <p>Appearance Date :<%= link_to appearance.episode.date, episode_path(appearance.episode) %></p><br>
  
   <p>Appearance Rating:<%= appearance.rating %><p> 

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImmersiveRailsAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>